site_name: WBQ's Blog
repo_url: https://github.com/water-wbq
repo_name: water-wbq
copyright: water-wbq
site_author: wbq
site_url: https://github.com/water-wbq/blog
# site_description: 路边野餐
google_analytics: ['UA-188482877-1', 'auto']
theme:
    name: material
    font: false
    custom_dir: docs/overrides
    logo: images/favicon.jpg
    favicon: images/favicon.jpg
    palette:
        primary: black
    features:
        - navigation.tabs
        - navigation.tabs.sticky
extra:
    disqus: binqingwu
extra_javascript:
#s    - js/config.js
    - https://cdn.bootcdn.net/ajax/libs/mathjax/3.1.0/es5/tex-mml-chtml.min.js
#    - http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true
plugins:
    - search
    - git-revision-date
